"""add_workspace_type_cron_jobs_user_timezone

Revision ID: 33262321f481
Revises: v017
Create Date: 2026-06-01 05:32:22.457206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33262321f481'
down_revision: Union[str, None] = 'v017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('natural_query', sa.Text(), nullable=False),
    sa.Column('cron_expr', sa.String(length=100), nullable=False),
    sa.Column('human_schedule', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=100), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_jobs_user_id'), 'cron_jobs', ['user_id'], unique=False)
    op.drop_index('ix_connector_definitions_slug', table_name='connector_definitions')
    op.create_unique_constraint(None, 'connector_definitions', ['slug'])
    op.drop_index('ix_kb_documents_status', table_name='kb_documents')
    op.create_index(op.f('ix_kb_documents_processing_status'), 'kb_documents', ['processing_status'], unique=False)
    op.add_column('users', sa.Column('timezone', sa.String(length=100), server_default='UTC', nullable=False))
    op.add_column('workspaces', sa.Column('workspace_type', sa.String(length=20), server_default='standard', nullable=False))
    op.drop_index('ix_workspaces_created_at', table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workspaces_created_at', 'workspaces', ['created_at'], unique=False)
    op.drop_column('workspaces', 'workspace_type')
    op.drop_column('users', 'timezone')
    op.drop_index(op.f('ix_kb_documents_processing_status'), table_name='kb_documents')
    op.create_index('ix_kb_documents_status', 'kb_documents', ['processing_status'], unique=False)
    op.drop_constraint(None, 'connector_definitions', type_='unique')
    op.create_index('ix_connector_definitions_slug', 'connector_definitions', ['slug'], unique=True)
    op.drop_index(op.f('ix_cron_jobs_user_id'), table_name='cron_jobs')
    op.drop_table('cron_jobs')
    # ### end Alembic commands ###
