"""add_task_description_agent_plan_to_cron_jobs

Revision ID: a43ee34d76f9
Revises: 33262321f481
Create Date: 2026-06-01 06:34:46.944113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a43ee34d76f9'
down_revision: Union[str, None] = '33262321f481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_jobs', sa.Column('task_description', sa.Text(), server_default='', nullable=False))
    op.add_column('cron_jobs', sa.Column('agent_plan', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_jobs', 'agent_plan')
    op.drop_column('cron_jobs', 'task_description')
    # ### end Alembic commands ###
